# Generated by Django 5.2.4 on 2025-07-10 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=25, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=25, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=25, verbose_name='Отчесво')),
                ('label', models.CharField(max_length=20, verbose_name='Ник')),
                ('level', models.CharField(max_length=3, verbose_name='Класс')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
